import Seo from '../components/Seo';
import PageHero from '../components/PageHero';

const sections = [
  {
    title: 'Introduction',
    body: [
      'BELLPHONESS ("we," "our," or "us") is committed to protecting your privacy. This Privacy Policy explains how your personal information is collected, used, and disclosed by BELLPHONESS.',
      'This Privacy Policy applies to our website and its associated subdomains (collectively, our "Service") alongside our application, BELLPHONESS. By accessing or using our Service, you signify that you have read, understood, and agree to our collection, storage, use, and disclosure of your personal information as described in this Privacy Policy and our Terms of Service.',
    ],
  },
  {
    title: 'Definitions and Key Terms',
    body: [
      'Cookie: a small amount of data generated by a website and saved by your web browser, used to identify your browser and remember information such as language preference or login details.',
      'Company: "Company," "we," "us," or "our" refers to AL JARAS ELECTRONICS TRADING LLC (M01, AYAL NASIR BLDG, NAIF, DEIRA, DUBAI, UAE).',
      'Country: where BELLPHONESS is based — United Arab Emirates.',
      'Device: any internet-connected device used to visit BELLPHONESS and use the services.',
      'Personal Data: any information that directly or indirectly allows for the identification of a natural person.',
      'Website: BELLPHONESS.COM.',
      'You: a person or entity registered with BELLPHONESS to use the Services.',
    ],
  },
  {
    title: 'What Information Do We Collect?',
    body: [
      'We collect information when you visit our website, register on our site, place an order, subscribe to our newsletter, respond to a survey, or fill out a form. We also collect information from mobile devices for a better user experience, though these features are optional.',
    ],
  },
  {
    title: 'How Do We Use The Information We Collect?',
    body: [
      'To personalize your experience and better respond to your individual needs.',
      'To improve our website based on the information and feedback we receive.',
      'To improve customer service and support.',
      'To process transactions.',
      'To administer a contest, promotion, survey, or other site feature.',
      'To send periodic emails.',
    ],
  },
  {
    title: 'Do We Share Information With Third Parties?',
    body: [
      'We may share information we collect with third parties such as advertisers, promotional partners, and service providers who help us host and maintain our servers, process payments, and fulfil orders. We are not in the business of selling customer data to others.',
      'We may disclose information to government or law enforcement officials where necessary to comply with applicable laws, protect our rights, or respond to legal process.',
    ],
  },
  {
    title: 'How Do We Use Your Email Address?',
    body: [
      'By submitting your email address, you agree to receive emails from us. You can opt out at any time using the unsubscribe link included in each email. We do not send unsolicited commercial emails.',
    ],
  },
  {
    title: 'How Long Do We Keep Your Information?',
    body: [
      'We keep your information only as long as needed to provide our Service and fulfil the purposes described in this policy, or as required by law.',
    ],
  },
  {
    title: 'How Do We Protect Your Information?',
    body: [
      'We use a variety of security measures including SSL encryption for sensitive data. Credit card and financial details are never kept on file after a transaction. We cannot, however, guarantee absolute security of any information transmitted to us.',
    ],
  },
  {
    title: 'International Data Transfers',
    body: [
      'BELLPHONESS is incorporated in the United Arab Emirates. Information collected may be transferred to and hosted in other countries. By using our Service, you consent to this transfer.',
    ],
  },
  {
    title: 'Can I Update or Correct My Information?',
    body: [
      'You can contact us to update, correct, or request deletion of your personal information by cancelling your account. To protect your privacy, we may take reasonable steps to verify your identity before making changes.',
    ],
  },
  {
    title: 'Cookies',
    body: [
      'BELLPHONESS uses cookies to identify areas of our website you have visited and to enhance performance and functionality. Most browsers can be set to disable cookies, though this may limit site functionality. We never place personally identifiable information in cookies.',
    ],
  },
  {
    title: "Kids' Privacy",
    body: [
      'If you are a parent or guardian and believe your child has provided us with Personal Data without your permission, please contact us. We will take steps to remove such information from our servers.',
    ],
  },
  {
    title: 'Governing Law',
    body: [
      'This Privacy Policy is governed by the laws of the Dubai International Financial Centre (DIFC), without regard to its conflict of laws provisions.',
    ],
  },
  {
    title: 'Changes to This Policy',
    body: [
      'We may update this Privacy Policy from time to time. We will notify you of any changes by posting the new policy on this page before it takes effect.',
    ],
  },
  {
    title: 'Contact Us',
    body: [
      'If you have any questions about this Privacy Policy, contact us via email at contact@BELLPHONESS.COM or visit www.BELLPHONESS.COM/contact.',
    ],
  },
];

export default function PrivacyPolicyPage() {
  return (
    <>
      <Seo
        title="Privacy Policy | BELL"
        description="Read BELL's privacy policy to understand how we collect, use, and protect your information."
      />
      <PageHero eyebrow="BELL / CUSTOMER CARE" title={<em>Privacy Policy</em>} />

      <article className="shell legal-page">
        <p className="eyebrow">LAST UPDATED</p>
        <h2>Your privacy matters to us.</h2>
        <p>
          AL JARAS ELECTRONICS TRADING LLC (trading as BELL) is licensed by Dubai Economy and
          Tourism. This policy explains how we handle your personal information.
        </p>

        {sections.map((section) => (
          <div key={section.title}>
            <h3>{section.title}</h3>
            {section.body.map((para, i) => (
              <p key={i}>{para}</p>
            ))}
          </div>
        ))}
      </article>
    </>
  );
}